# Generated by Django 4.0.10 on 2023-06-18 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории товара', max_length=200)),
                ('summary', models.TextField(help_text='Введите краткое описание категории', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название товара', max_length=200)),
                ('summary', models.CharField(help_text='Введите краткое описание товара', max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите цену товара', max_digits=10)),
                ('quantity', models.PositiveIntegerField(help_text='Введите количество товара')),
                ('time_added', models.DateTimeField(auto_now_add=True, help_text='Время добавления товара')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='Время обновления товара')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название склада', max_length=200)),
                ('address', models.CharField(help_text='Введите адрес склада', max_length=200)),
                ('products', models.ManyToManyField(related_name='warehouses', to='management.product')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(help_text='Введите контактное лицо', max_length=200)),
                ('address', models.CharField(help_text='Введите адрес поставщика', max_length=200)),
                ('tel', models.CharField(help_text='Введите номер телефона', max_length=20)),
                ('name', models.ForeignKey(help_text='Введите название поставщика', max_length=200, on_delete=django.db.models.deletion.CASCADE, to='management.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(help_text='Идентификатор склада', on_delete=django.db.models.deletion.CASCADE, to='management.warehouse'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Введите количество товара')),
                ('date', models.DateField(auto_now_add=True, help_text='Время создания заказа')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Введите количество поставляемого товара')),
                ('date', models.DateField(help_text='Выберите дату доставки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Category_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.product')),
            ],
        ),
    ]
