# Generated by Django 4.0.10 on 2023-06-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Идентификатор склада', null=True, on_delete=django.db.models.deletion.CASCADE, to='management.warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='warehouses', to='management.product'),
        ),
    ]
