# Generated by Django 4.0.10 on 2023-06-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_product_warehouse_alter_warehouse_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(help_text='Введите название поставщика', max_length=200),
        ),
    ]
