# Generated by Django 4.0.10 on 2023-06-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_product_time_added_alter_product_update_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(help_text='Выберите дату поставки'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(help_text='Введите наименование организации', max_length=200),
        ),
    ]
