# Generated by Django 4.0.10 on 2023-06-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_delivery_date_alter_supplier_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='products',
        ),
    ]
