# Generated by Django 4.0.10 on 2023-06-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_warehouse_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': ('Category',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': ('Delivery',), 'verbose_name_plural': 'Deliveries'},
        ),
    ]
