# Generated by Django 4.0.10 on 2023-06-23 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_category_options_alter_delivery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_product',
            options={'verbose_name': ('Category_Product',), 'verbose_name_plural': 'Categories_Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Идентификатор склада', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='management.warehouse'),
        ),
    ]
