# Generated by Django 4.0.10 on 2023-06-27 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_category_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Введите количество товара на складе')),
            ],
            options={
                'verbose_name': 'ProductWarehouse',
                'verbose_name_plural': 'ProductWarehouses',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='category_product',
            options={'verbose_name': 'Category_Product', 'verbose_name_plural': 'Categories_Products'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='time_added',
        ),
        migrations.RemoveField(
            model_name='product',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='product',
            name='warehouses',
            field=models.ManyToManyField(blank=True, help_text='Склады', related_name='products', through='management.ProductWarehouse', to='management.warehouse'),
        ),
        migrations.AddField(
            model_name='productwarehouse',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.product'),
        ),
        migrations.AddField(
            model_name='productwarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.warehouse'),
        ),
    ]
