# Generated by Django 4.0.10 on 2023-06-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_delivery_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warehouses',
            field=models.ManyToManyField(blank=True, help_text='Склады', related_name='products', through='management.Delivery', to='management.warehouse'),
        ),
        migrations.DeleteModel(
            name='ProductWarehouse',
        ),
    ]
