# Generated by Django 4.0.10 on 2023-06-27 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_product_warehouses_delete_productwarehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Введите количество товара на складе')),
            ],
            options={
                'verbose_name': 'ProductWarehouse',
                'verbose_name_plural': 'ProductWarehouses',
            },
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='delivery',
            name='warehouse',
            field=models.ManyToManyField(help_text='Выберите склад для поставки', to='management.warehouse'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouses',
            field=models.ManyToManyField(blank=True, help_text='Склады', related_name='products', through='management.ProductWarehouse', to='management.warehouse'),
        ),
        migrations.AddField(
            model_name='productwarehouse',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.product'),
        ),
        migrations.AddField(
            model_name='productwarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.warehouse'),
        ),
    ]
