# Generated by Django 4.0.10 on 2023-06-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_remove_delivery_warehouse_delivery_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='warehouse',
        ),
    ]
