# Generated by Django 4.0.10 on 2023-06-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_remove_delivery_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Категории', related_name='products', through='management.Category_Product', to='management.category'),
        ),
        migrations.AlterField(
            model_name='productwarehouse',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Введите количество товара на складе'),
        ),
    ]
